import type { UiPaymentRow } from '../types/payments'

export const MOCK_PAYMENTS: UiPaymentRow[] = [
  {
    id: 'pay_abc123',
    createdAt: '2024-01-15T09:30:00Z',
    customerLabel: 'Jane Doe',
    customerEmail: 'jane.doe@example.com',
    method: 'card',
    amountLabel: '25.00 USD',
    normalizedStatus: 'COMPLETED',
    rawStatus: 'SUCCEEDED',
    errorMessage: '',
    blockchain: 'solana',
  },
  {
    id: 'pay_def456',
    createdAt: '2024-01-15T10:00:00Z',
    customerLabel: 'john@example.com',
    customerEmail: 'john@example.com',
    method: 'bank_transfer',
    amountLabel: '100.00 USD',
    normalizedStatus: 'FAILED',
    rawStatus: 'DECLINED',
    errorMessage: 'Insufficient funds',
    blockchain: 'eth',
  },
  {
    id: 'pay_ghi789',
    createdAt: '2024-01-16T12:45:00Z',
    customerLabel: 'alice@example.com',
    customerEmail: 'alice@example.com',
    method: 'pix',
    amountLabel: '37.50 USD',
    normalizedStatus: 'PENDING',
    rawStatus: 'INITIATED',
    errorMessage: '',
    blockchain: 'polygon',
  },
  {
    id: 'pay_jkl012',
    createdAt: '2024-01-17T08:15:00Z',
    customerLabel: 'Bob Lee',
    customerEmail: 'bob@example.com',
    method: 'crypto',
    amountLabel: '420.00 USD',
    normalizedStatus: 'COMPLETED',
    rawStatus: 'SETTLED',
    errorMessage: '',
    blockchain: 'base',
  },
  {
    id: 'pay_mno345',
    createdAt: '2024-01-18T18:05:00Z',
    customerLabel: 'Unknown customer',
    method: 'instant',
    amountLabel: '58.99 USD',
    normalizedStatus: 'OTHER',
    rawStatus: 'REGISTERED',
    errorMessage: 'Processing delay',
    blockchain: 'arbitrum',
  },
] // add 3–5 more

